//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAN
    {
        public string MaTiec { get; set; }
        public string MaBan { get; set; }
        public Nullable<int> DongiaBan { get; set; }
        public Nullable<int> SLBan { get; set; }
        public Nullable<int> Sobandutru { get; set; }
        public Nullable<int> Sobandutrudadung { get; set; }
        public Nullable<int> ThanhTienBan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
