//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETMONAN
    {
        public string MaTiec { get; set; }
        public string MaMonAN { get; set; }
        public Nullable<int> DongiaMonan { get; set; }
        public Nullable<int> SLMonan { get; set; }
        public Nullable<int> ThanhTienMonan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual MONAN MONAN { get; set; }
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
