//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDV
    {
        public string MaTiec { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> DongiaDV { get; set; }
        public Nullable<int> SLDichvu { get; set; }
        public Nullable<int> ThanhTienDV { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
