//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBCDOANHTHUTHEOTHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTBCDOANHTHUTHEOTHANG()
        {
            this.CTBCTHUCHITHEONGAYs = new HashSet<CTBCTHUCHITHEONGAY>();
        }
    
        public string MaBCDoanhthuthang { get; set; }
        public Nullable<System.DateTime> Ngaybaocao { get; set; }
        public Nullable<int> Soluongtieccuoi { get; set; }
        public Nullable<int> Doanhthuthangnay { get; set; }
        public Nullable<int> Doanhthuthangtruoc { get; set; }
        public Nullable<float> Tiledoanhthuthang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBCTHUCHITHEONGAY> CTBCTHUCHITHEONGAYs { get; set; }
    }
}
