//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MaHopdong { get; set; }
        public string MaKH { get; set; }
        public string MaTiec { get; set; }
        public string TenHopdong { get; set; }
        public Nullable<System.DateTime> Ngayky { get; set; }
        public string TinhTrangHopdong { get; set; }
        public string Ghichu { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
