//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIECCUOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIECCUOI()
        {
            this.CHITIETBANs = new HashSet<CHITIETBAN>();
            this.CHITIETDVs = new HashSet<CHITIETDV>();
            this.CHITIETMONANs = new HashSet<CHITIETMONAN>();
            this.HOPDONGs = new HashSet<HOPDONG>();
        }
    
        public string MaTiec { get; set; }
        public string MaKH { get; set; }
        public string MaSanh { get; set; }
        public string MaCa { get; set; }
        public string MaHD { get; set; }
        public string MaBCThuchi { get; set; }
        public string Tenchure { get; set; }
        public string Tencodau { get; set; }
        public string TinhtrangTC { get; set; }
        public Nullable<System.DateTime> NgayTCtiec { get; set; }
        public Nullable<System.DateTime> Ngaythanhtoan { get; set; }
        public Nullable<int> TongTienDV { get; set; }
        public Nullable<int> TongTienMonAn { get; set; }
        public Nullable<int> TongTienBan { get; set; }
        public Nullable<int> Tiencoc { get; set; }
        public Nullable<int> Tienphat { get; set; }
        public Nullable<int> TongTienHD { get; set; }
        public Nullable<int> TienKhachdua { get; set; }
        public Nullable<int> TienThoiKhach { get; set; }
    
        public virtual CA CA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAN> CHITIETBANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDV> CHITIETDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETMONAN> CHITIETMONANs { get; set; }
        public virtual CTBCTHUCHITHEONGAY CTBCTHUCHITHEONGAY { get; set; }
        public virtual HOADON HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANH SANH { get; set; }
    }
}
