//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTCBasic.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTiecCuoiEntities : DbContext
    {
        public QLTiecCuoiEntities()
            : base("name=QLTiecCuoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BAN> BANs { get; set; }
        public virtual DbSet<BIENLAI> BIENLAIs { get; set; }
        public virtual DbSet<CA> CAs { get; set; }
        public virtual DbSet<CHITIETBAN> CHITIETBANs { get; set; }
        public virtual DbSet<CHITIETDV> CHITIETDVs { get; set; }
        public virtual DbSet<CHITIETMONAN> CHITIETMONANs { get; set; }
        public virtual DbSet<CTBCBAOTRISANH> CTBCBAOTRISANHs { get; set; }
        public virtual DbSet<CTBCDOANHTHUTHEOTHANG> CTBCDOANHTHUTHEOTHANGs { get; set; }
        public virtual DbSet<CTBCNHAPKHO> CTBCNHAPKHOes { get; set; }
        public virtual DbSet<CTBCTHUCHITHEONGAY> CTBCTHUCHITHEONGAYs { get; set; }
        public virtual DbSet<CTBCXUATKHO> CTBCXUATKHOes { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<MONAN> MONANs { get; set; }
        public virtual DbSet<SANH> SANHs { get; set; }
        public virtual DbSet<TIECCUOI> TIECCUOIs { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
